name: "GCP on-demand container scan"
description: "Scan container using GCP"


inputs:
  container_name:
    description: "Container name tag which we want to scan"
    required: true
  slackWebhook:
    description: "Preferred slack channel webhook to send notifications"
    required: true
runs:
  using: composite
  steps:
    - name: Checkout Current Directory
      uses: actions/checkout@v3
      path: ./container-scan/
    - name: Test Step
      working-directory: ./container-scan/
      run: ls .
      shell: bash