name: "Container Scan"
author: "ridedott"
description: "on-demand container scanning using GCP on-demand API"
branding:
  icon: "alert-triangle"
  color: "blue"
  
inputs:
  containerTag:
    description: "Container name tag which we want to scan"
    required: true
  slackWebhook:
    description: "Preferred slack channel webhook to send notifications"
    required: true
  githubUrl:
    description: "Github Action github url"
    required: true
  workload_identity_provider:
    description: "Workload Idendity Provider"
    required: true
  service_account:
    description: "Service Account"
    required: true
runs:
  using: composite
  steps:
    - name: Add GITHUB run path
      run: echo "${{ github.action_path }}" >> $GITHUB_PATH 
      shell: bash
    - name: Container Scan
      run: scan.sh
      shell: bash
      env:
        containerTag: ${{ inputs.containerTag }}
        slackWebhook: ${{ inputs.slackWebhook }}
        githubUrl: ${{ inputs.githubUrl }}
